version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 movie_recommendation.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A movie_recommendation worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data: